# Generated by Django 5.1.5 on 2025-03-24 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autore',
            options={'verbose_name_plural': 'Autori'},
        ),
        migrations.AlterModelOptions(
            name='genere',
            options={'verbose_name_plural': 'Generi'},
        ),
        migrations.AlterModelOptions(
            name='libro',
            options={'verbose_name_plural': 'Libri'},
        ),
        migrations.AddField(
            model_name='libro',
            name='data_acquisto',
            field=models.DateField(null=True, verbose_name='Data di acquisto'),
        ),
    ]
